version: '3.7'

services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_test_link
      - POSTGRES_HOST=POSTGRES_HOST
    volumes:
      - pgdata:/data/postgres
    ports:
      - '5433:5432'

  api:
    container_name: api_feed_link
    build: .
    restart: always
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - '3000:3000'
    command: bash -c 'while !</dev/tcp/db_desafio_suflex/5432; do sleep 1; done;yarn typeorm migrtion:run -d src/data-source.ts && yarn dev'
volumes:
  pgdata:
    driver: local
